apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workbench.fullname" . }}
  labels:
    {{- include "workbench.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "workbench.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "workbench.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3030
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "workbench.envVars" . | trim | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["sh", "-c", "npx nodemon server.js"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /test
              port: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "workbench.envVars" . | trim | nindent 12 }}