# Default values for ai-demo-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 012629307706.dkr.ecr.us-east-1.amazonaws.com/ai-demo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

selectorLabels:
  app: ai-demo-ui
  env: ssprod
  region: us-east-1

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: "443"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:012629307706:certificate/45637da7-e010-4940-97a9-f21780c83e58"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"


ingress:
  enabled: false
  annotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: "300m"
    memory: "1000Mi"
  limits:
    cpu: "500m"
    memory: "1200Mi"

nodeSelector: {}

tolerations: []

affinity: {}

envVars:
  - name: PIM_UI_URL
    value: https://pim.unbxd.io
  - name: CONSOLE_PROXY_URL
    value: https://console.unbxd.io
  - name: CONSOLE_UI_AWS_URL
    value: https://console-nam.unbxd.io
  - name: CONSOLE_UI_GCP_URL
    value: https://console-g-nam.unbxd.io
  - name: CONSOLE_US_AWS_URL
    value: https://console-nam.unbxd.io
  - name: CONSOLE_US_GCP_URL
    value: https://console-g-nam.unbxd.io
  - name: CONSOLE_UK_AWS_URL
    value: https://console-uk.unbxd.io
  - name: CONSOLE_SG_AWS_URL
    value: https://console-apac.unbxd.io
  - name: CONSOLE_ANZ_AWS_URL
    value: https://console-anz.unbxd.io
  - name: SEARCH_URL
    value: https://search.unbxd.io
  - name: SHOPIFY_ADMIN_URL
    value: https://search-pimapps.unbxd.io/admin
  - name: SEGMENT_WRITE_KEY
    value: hn4ADiVzatWGqpKsQWBGBG9zJxMKYq8b
  - name: ENABLED_REGIONS
    value: us,us-gcp,au,uk,sg
  - name: CURRENT_REGION
    value: us
