apiVersion: v1
kind: Service
metadata:
  name: aidemo
  labels:
    region: {{ .Values.region }}
    app: {{ .Values.app }}
    env: {{ .Values.env }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "aidemo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
