apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdk-qa-framework.fullname" . }}
  labels:
    {{- include "sdk-qa-framework.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      name: "https"
      protocol: TCP
  selector:
    {{- include "sdk-qa-framework.selectorLabels" . | nindent 4 }}
